development:
  adapter: mysql2
  encoding: utf8
  database: mathgame
  pool: 5
  username: 
  password:
test:
  adapter: mysql2
  encoding: utf8
  database: mathgame
  pool: 5
  username:
  password:
production:
  adapter: mysql2
  encoding: utf8
  database: mathgame
  pool: 5
  username:
  password:
